import type { RecentTransaction } from "./types";

export const recentTransactions: RecentTransaction[] = [
    {
        id: "1",
        title: "Amazon",
        category: "Shopping",
        accountName: "ICICI Credit Card",
        amount: 1_899,
        type: "expense",
        date: new Date("2026-07-12T18:45:00"),
        icon: "bag-handle-outline",
    },
    {
        id: "2",
        title: "Credit Card Payment",
        category: "Card Payment",
        accountName: "SBI Bank",
        amount: 5_000,
        type: "payment",
        date: new Date("2026-07-11T14:20:00"),
        icon: "swap-horizontal-outline",
    },
    {
        id: "3",
        title: "BigBasket",
        category: "Groceries",
        accountName: "HDFC Bank",
        amount: 2_340,
        type: "expense",
        date: new Date("2026-07-10T19:10:00"),
        icon: "cart-outline",
    },
    {
        id: "4",
        title: "Fuel",
        category: "Auto",
        accountName: "ICICI Credit Card",
        amount: 1_250,
        type: "expense",
        date: new Date("2026-07-10T11:35:00"),
        icon: "car-outline",
    },
    {
        id: "5",
        title: "Salary",
        category: "Income",
        accountName: "SBI Bank",
        amount: 13_000,
        type: "income",
        date: new Date("2026-07-09T09:15:00"),
        icon: "wallet-outline",
    },
];